import { ScanResult, Finding, DiffResult, RiskLevel } from '../types';

const RISK_ICONS: Record<RiskLevel, string> = {
  high: '🔴',
  medium: '🟡',
  low: '🔵',
  good: '🟢',
};

const RISK_LABELS: Record<RiskLevel, string> = {
  high: 'HIGH',
  medium: 'MEDIUM',
  low: 'LOW',
  good: 'GOOD',
};

function riskBadge(risk: RiskLevel): string {
  return `${RISK_ICONS[risk]} ${RISK_LABELS[risk]}`;
}

function riskScoreLabel(score: number): string {
  if (score <= 10) return '🟢 Excellent';
  if (score <= 25) return '🔵 Good';
  if (score <= 50) return '🟡 Moderate';
  if (score <= 75) return '🟠 High';
  return '🔴 Critical';
}

function renderFinding(f: Finding): string {
  const lines: string[] = [];
  lines.push(`### ${riskBadge(f.risk)} ${f.title}`);
  lines.push('');
  lines.push(`**ISO 27001 Clause:** ${f.isoClause} — ${f.isoClauseName}`);
  lines.push(`**Module:** ${f.module}`);
  lines.push(`**Finding ID:** ${f.id}`);
  if (f.autoFixable) {
    lines.push('**Auto-fixable:** Yes (use `--fix` flag)');
  }
  lines.push('');
  lines.push(f.description);
  lines.push('');

  if (f.details.length > 0) {
    lines.push('**Details:**');
    for (const d of f.details) {
      lines.push(`- ${d}`);
    }
    lines.push('');
  }

  lines.push(`**Recommendation:** ${f.recommendation}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  return lines.join('\n');
}

export function generateMarkdownReport(result: ScanResult): string {
  const lines: string[] = [];

  lines.push('# OpenClaw ISO 27001 Security Compliance Report');
  lines.push('');
  lines.push(`**Scan Date:** ${new Date(result.timestamp).toLocaleString()}`);
  lines.push(`**Hostname:** ${result.hostname}`);
  lines.push(`**Platform:** ${result.platform}`);
  lines.push('');

  // Executive Summary
  lines.push('## Executive Summary');
  lines.push('');
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Risk Score | ${result.summary.riskScore}/100 ${riskScoreLabel(result.summary.riskScore)} |`);
  lines.push(`| Total Findings | ${result.summary.totalFindings} |`);
  lines.push(`| 🔴 High Risk | ${result.summary.high} |`);
  lines.push(`| 🟡 Medium Risk | ${result.summary.medium} |`);
  lines.push(`| 🔵 Low / Info | ${result.summary.low} |`);
  lines.push(`| 🟢 Good | ${result.summary.good} |`);
  lines.push('');

  // Findings by module
  const moduleNames: Record<string, string> = {
    cryptography: 'A.8 Cryptography',
    'access-control': 'A.9 Access Control',
    communications: 'A.10 Communications Security',
    operations: 'A.12 Operations Security',
    system: 'A.13 System Security',
  };

  for (const [mod, findings] of Object.entries(result.modules)) {
    if (findings.length === 0) continue;

    lines.push(`## ${moduleNames[mod] || mod}`);
    lines.push('');

    // Sort by risk: high first
    const sorted = [...findings].sort((a, b) => {
      const order: Record<RiskLevel, number> = { high: 0, medium: 1, low: 2, good: 3 };
      return order[a.risk] - order[b.risk];
    });

    for (const f of sorted) {
      lines.push(renderFinding(f));
    }
  }

  // Footer
  lines.push('---');
  lines.push('');
  lines.push('*Generated by [openclaw-iso27001](https://github.com/openclaw/openclaw-iso27001) — ISO 27001:2022 compliance scanner for OpenClaw AI agents.*');

  return lines.join('\n');
}

export function generateDiffReport(diff: DiffResult): string {
  const lines: string[] = [];

  lines.push('# OpenClaw ISO 27001 — Scan Diff Report');
  lines.push('');
  lines.push(`**Previous Scan:** ${new Date(diff.previousTimestamp).toLocaleString()}`);
  lines.push(`**Current Scan:** ${new Date(diff.currentTimestamp).toLocaleString()}`);
  lines.push('');

  // Score change
  const scoreDelta = diff.currentScore - diff.previousScore;
  const trend = scoreDelta < 0 ? '📉 Improved' : scoreDelta > 0 ? '📈 Worsened' : '➡️ Unchanged';
  lines.push(`## Risk Score: ${diff.previousScore} → ${diff.currentScore} (${trend})`);
  lines.push('');

  // New findings
  if (diff.newFindings.length > 0) {
    lines.push(`## ⚠️ New Findings (${diff.newFindings.length})`);
    lines.push('');
    for (const f of diff.newFindings) {
      lines.push(renderFinding(f));
    }
  }

  // Resolved findings
  if (diff.resolvedFindings.length > 0) {
    lines.push(`## ✅ Resolved Findings (${diff.resolvedFindings.length})`);
    lines.push('');
    for (const f of diff.resolvedFindings) {
      lines.push(`- ~~${riskBadge(f.risk)} ${f.title}~~ — ${f.id}`);
    }
    lines.push('');
  }

  // Unchanged
  lines.push(`## Unchanged Findings: ${diff.unchangedFindings.length}`);
  lines.push('');

  return lines.join('\n');
}
